### ISSUE TITLE
最新版本提交工单后会自动跳转

### ISSUE THREAD

**Issue by lixiaolong2** [lazyphp/PESCMS-Ticket#1]
最新版本提交工单后会自动跳转

提交完毕工单显示工单编号的时候，还没看清楚编号就会自动刷新网页。如果嵌入到其他网站中，还会自动跳到/?m=Submit&a=ticket这个链接，导致工单提交后会自动跳出网页并显示错误

**Comment by lazyphp** [comment]
跨域工单暂时下架处理。
