### ISSUE TITLE
关于工单分配的问题

### ISSUE THREAD

**Issue by 0000005** [lazyphp/PESCMS-Ticket#10]
我们现在有这样一个需求：
每个人值班一天，也就意味着这一天，所有的售后都由那一个人处理。
pescms-ticket有什么办法实现类似的功能吗？
我看到“自动分单逻辑”只有“随机”和“平均”两种策略。

**Comment by 0000005** [comment]
谢谢

**Comment by lazyphp** [comment]
这个自行扩展分单逻辑。现在还没将这部分 自定义扩展出来，具体你要翻看代码。

**Comment by 0000005** [comment]
好的
