### ISSUE TITLE
关于“新增常见问题”的问题

### ISSUE THREAD

**Issue by 0000005** [lazyphp/PESCMS-Ticket#16]
我们想在fqa表中新增一个创建人的字段，但是不知道改哪个文件。
`?g=Ticket&m=Fqa&a=action&back_url=Lz9nPVRpY2tldCZtPUZxYSZhPWluZGV4`
这种路由很奇怪，能指点一下，改哪个文件吗？

**Comment by lazyphp** [comment]
参考：https://www.pescms.com/d/index/15.html

**Comment by 0000005** [comment]
![image](https://user-images.githubusercontent.com/9690089/126453146-0367f18d-5623-4b28-b2a3-7bc2f452c558.png)
没看到模型管理的入口啊

**Comment by lazyphp** [comment]
你不看文档的吗？文档有说入口啊。
https://www.pescms.com/d/v/2.5/15/76.html
若菜单没有找到模型管理入口，可以手动访问：/?g=当前管理后台的组别&m=Model&a=index

**Comment by 0000005** [comment]
感谢
不好意思，是我傻逼了
