### ISSUE TITLE
建议增加新工单提醒

### ISSUE THREAD

**Issue by lixiaolong2** [lazyphp/PESCMS-Ticket#2]
有时并没办法时时刻刻刷新网页，建议用户提交或者回复工单的时候增加给管理员推送邮件，提醒有新客户发工单了。

**Comment by lazyphp** [comment]
现阶段你可以在\Model\Ticket.php 的insert() 方法 做一个 插入到 pes_send 表 的动作。
这个问题在未来版本会改善，下半年里面一直在忙工作，没太多精力维护PT。
