### ISSUE TITLE
新版出现单选下拉不能选中数据

### ISSUE THREAD

**Issue by acutecat** [lazyphp/PESCMS-Ticket#3]
工单表单同时有单选和复选，再添加单选下拉会出现不能选中数据，设置非必选之后提交，在后台看到的单选、多选和下拉都是默认第一个选项，我目前也不能确定这个是不是bug，所以来发issue问下，有没有出现相同问题的。

**Comment by lazyphp** [comment]
经过复现，没有出现这个问题。
