### ISSUE TITLE
能否增加一个钉钉通知呢？

### ISSUE THREAD

**Issue by yanbin0304** [lazyphp/PESCMS-Ticket#4]

**Comment by yanbin0304** [comment]
我想用钉钉通知，觉得这样更快捷方便一些

**Comment by lazyphp** [comment]
如果你可以提供钉钉的API参数，我可以帮你添加接口。

**Comment by yanbin0304** [comment]
钉钉官网你可以看一下。API参数我有的https://open-doc.dingtalk.com/microapp/serverapi2/qf2nxq

**Comment by yanbin0304** [comment]
麻烦了

**Comment by lazyphp** [comment]
你加我QQ 201418824 详聊。我先看看钉钉的文档。

**Comment by lazyphp** [comment]
dev-1.3.2分支 目前对接了钉钉了。消息通知选用：工作通知消息 。   
机器人的方式不太合适多个客服分组的应用，所以没有选用。  
同时我发现钉钉在发送方面有限制，不知道钉钉以后会不会解除。
