### ISSUE TITLE
请问一下这里提交为什么会丢失提交的数据变为全选

### ISSUE THREAD

**Issue by acutecat** [lazyphp/PESCMS-Ticket#5]
![image](https://user-images.githubusercontent.com/33690786/59176791-c2b78480-8b8c-11e9-83ca-b72fb189e547.png)
在这里选择一项作为触发值，提交之后就会变成全选，是什么原因造成的，是我用的浏览器不对吗？我这里用的是Chrome浏览器
![image](https://user-images.githubusercontent.com/33690786/59176908-07432000-8b8d-11e9-879f-1c01d9eef686.png)

**Comment by lazyphp** [comment]
本地复现了一次，并没有出现提交后会全选的情况。
联动表单字段的 工单表单的选项值 是什么呢？

**Comment by acutecat** [comment]
联动工单表里面也是单选按钮，每个单选点开之后就会出现另外的更细的单选操作

**Comment by acutecat** [comment]
![( `FE``~_ 1JMJ8J$)06FZ2](https://user-images.githubusercontent.com/33690786/59194204-d8dc3980-8bba-11e9-843c-ca479e2b125d.gif)
会出现这种就会出现这种情况呢

**Comment by lazyphp** [comment]
我看了，你的值有问题。
你看 工单表单的选项值的说明， 名称|值 。例如：
设备重启|1   右边你给他一个值，可以1或者 设备重启|设备重启

**Comment by acutecat** [comment]
好的，谢谢，问题已解决。
