### ISSUE TITLE
安装后密码始终错误，太折腾了

### ISSUE THREAD

**Issue by peaceanddemocracy** [lazyphp/PESCMS-Ticket#6]
能不能去掉密码的加密功能？或者实在不行用md5加密也行，程序的加密貌似在虚拟主机和不同环境中运行有问题

**Comment by lazyphp** [comment]
MD5有大量彩虹表可破解，不会为此降低安全性的。
帐号密码错误请参考：https://www.pescms.com/d/v/1.0/10/123.html

**Comment by peaceanddemocracy** [comment]
> MD5有大量彩虹表可破解，不会为此降低安全性的。
> 帐号密码错误请参考：https://www.pescms.com/d/v/1.0/10/123.html

是把代码直接加在CoreFunc文件中么，大佬能不能给个带generatePwd(.....) 在内的示例，试了多次F12无法显示密码，不知道哪里出问题了

**Comment by lazyphp** [comment]
你按照文档教程，将获得的密文 填写到 数据库的管理员表 密码字段。再执行登录就正常了。如果还是提示密码错误，你按照文档的教程，断点调试登录判断的逻辑。
