### ISSUE TITLE
一款不错的工单管理系统

### ISSUE THREAD

**Issue by liugddx** [lazyphp/PESCMS-Ticket#7]
希望有其他语言版本的支撑。

**Comment by lazyphp** [comment]
多语言切换暂时没计划。以前有做过多语言版本，太影响开发进度，所以移除了。

**Comment by liugddx** [comment]
> 多语言切换暂时没计划。以前有做过多语言版本，太影响开发进度，所以移除了。

有没有中英文切换的开发计划？
