### ISSUE TITLE
安装界面会报错

### ISSUE THREAD

**Issue by 0000005** [lazyphp/PESCMS-Ticket#8]
![image](https://user-images.githubusercontent.com/9690089/125250189-8a18a500-e328-11eb-97a9-7cee6b767bb6.png)

**Comment by lazyphp** [comment]
升级PHP版本为7.X 
注意：目前PHP 8.0无法正常运行。

**Comment by 0000005** [comment]
![image](https://user-images.githubusercontent.com/9690089/125250591-014e3900-e329-11eb-95ad-e168d33903f7.png)

**Comment by 0000005** [comment]
我的版本是5.6

**Comment by lazyphp** [comment]
官网此处忘记调整过来了。1.3.9版本起安装需要PHP7.X版本。
