### ISSUE TITLE
关于工单模型的问题

### ISSUE THREAD

**Issue by 0000005** [lazyphp/PESCMS-Ticket#9]
![image](https://user-images.githubusercontent.com/9690089/125255785-5fc9e600-e32e-11eb-99d0-3f83056f5d37.png)

![image](https://user-images.githubusercontent.com/9690089/125255830-6b1d1180-e32e-11eb-9707-10d2debf499b.png)

1、联系方式选择微信，然后前台并未显示微信。
2、另外能否提供一种自定义的 联系方式，不被正则给限制住。
谢谢

**Comment by lazyphp** [comment]
1. 微信需要用微信客户端打开才会显示
2. 目前版本支持自定义。由于文档还没编写完，所以没有宣传。 你需要的话，可以访问 \Expand\OtherNotice.php 。里面有较为简单的注释说明。
